#############################################################################
# Makefile for building: simple
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? ????. 19 22:50:07 2011
# Project:  /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/simple.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/simple.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I/media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple -I/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src -I/home/linko/Загрузки/qtcopydialog-build-desktop/examples/simple/. -I/home/linko/Загрузки/qtcopydialog-build-desktop/examples/simple/. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.cpp \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.cpp \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/main.cpp 
OBJECTS       = qtcopydialog.o \
		qtfilecopier.o \
		main.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/common.pri \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/simple.pro
QMAKE_TARGET  = simple
DESTDIR       = 
TARGET        = simple

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qtcopydialog.h ui_qtoverwritedialog.h ui_qtotherdialog.h ui_filedialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/simple.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/common.pri \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/simple.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/media/C811-5AB5/qtcopydialog-2.2_1-opensource/common.pri:
/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.pri:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/simple.pro

dist: 
	@$(CHK_DIR_EXISTS) /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0 || $(MKDIR) /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0/ && $(COPY_FILE) --parents /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.h /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0/ && $(COPY_FILE) --parents /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.cpp /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.cpp /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/main.cpp /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0/ && $(COPY_FILE) --parents /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.ui /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtoverwritedialog.ui /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtotherdialog.ui /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/filedialog.ui /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0/ && (cd `dirname /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0` && $(TAR) simple1.0.0.tar simple1.0.0 && $(COMPRESS) simple1.0.0.tar) && $(MOVE) `dirname /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0`/simple1.0.0.tar.gz . && $(DEL_FILE) -r /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/.tmp/simple1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qtcopydialog.cpp moc_qtfilecopier.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtcopydialog.cpp moc_qtfilecopier.cpp
moc_qtcopydialog.cpp: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.h -o moc_qtcopydialog.cpp

moc_qtfilecopier.cpp: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h -o moc_qtfilecopier.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: qtcopydialog.moc qtfilecopier.moc main.moc
compiler_moc_source_clean:
	-$(DEL_FILE) qtcopydialog.moc qtfilecopier.moc main.moc
qtcopydialog.moc: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.h \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h \
		ui_qtcopydialog.h \
		ui_qtoverwritedialog.h \
		ui_qtotherdialog.h \
		moc_qtcopydialog.cpp \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.cpp -o qtcopydialog.moc

qtfilecopier.moc: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h \
		moc_qtfilecopier.cpp \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.cpp -o qtfilecopier.moc

main.moc: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.h \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h \
		ui_filedialog.h \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/main.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/main.cpp -o main.moc

compiler_uic_make_all: ui_qtcopydialog.h ui_qtoverwritedialog.h ui_qtotherdialog.h ui_filedialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qtcopydialog.h ui_qtoverwritedialog.h ui_qtotherdialog.h ui_filedialog.h
ui_qtcopydialog.h: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.ui
	/usr/bin/uic-qt4 /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.ui -o ui_qtcopydialog.h

ui_qtoverwritedialog.h: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtoverwritedialog.ui
	/usr/bin/uic-qt4 /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtoverwritedialog.ui -o ui_qtoverwritedialog.h

ui_qtotherdialog.h: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtotherdialog.ui
	/usr/bin/uic-qt4 /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtotherdialog.ui -o ui_qtotherdialog.h

ui_filedialog.h: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/filedialog.ui
	/usr/bin/uic-qt4 /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/filedialog.ui -o ui_filedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

qtcopydialog.o: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.cpp /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.h \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h \
		ui_qtcopydialog.h \
		ui_qtoverwritedialog.h \
		ui_qtotherdialog.h \
		qtcopydialog.moc \
		moc_qtcopydialog.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtcopydialog.o /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.cpp

qtfilecopier.o: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.cpp /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h \
		qtfilecopier.moc \
		moc_qtfilecopier.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtfilecopier.o /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.cpp

main.o: /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/main.cpp /media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtcopydialog.h \
		/media/C811-5AB5/qtcopydialog-2.2_1-opensource/src/qtfilecopier.h \
		ui_filedialog.h \
		main.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o /media/C811-5AB5/qtcopydialog-2.2_1-opensource/examples/simple/main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

